# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.network "private_network", ip: "10.0.0.20"
  config.vm.provider "virtualbox" do |v|
#  config.vm.provider "vmware_workstation" do |v|
    #v.host = "webserver"
    #v.nested = true
    v.gui = false
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "./puppet", "/opt/puppet"

  config.vm.provision "shell", inline: 
    $script = <<SCRIPT
    
    echo Shell provisioning...
    sudo apt-get update
    sudo apt-get install puppet -y
SCRIPT

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "puppet"
    puppet.manifest_file = "default.pp"
  end
end
